/* Generated By:JavaCC: Do not edit this line. SGBDParserConstants.java */
package fr.insarouen.iti.prog.sgbd.parseur;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SGBDParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CREATE = 6;
  /** RegularExpression Id. */
  int TABLE = 7;
  /** RegularExpression Id. */
  int DROP = 8;
  /** RegularExpression Id. */
  int INSERT = 9;
  /** RegularExpression Id. */
  int INTO = 10;
  /** RegularExpression Id. */
  int VALUES = 11;
  /** RegularExpression Id. */
  int DELETE = 12;
  /** RegularExpression Id. */
  int FROM = 13;
  /** RegularExpression Id. */
  int WHERE = 14;
  /** RegularExpression Id. */
  int SELECT = 15;
  /** RegularExpression Id. */
  int AS = 16;
  /** RegularExpression Id. */
  int TABLES = 17;
  /** RegularExpression Id. */
  int EXIT = 18;
  /** RegularExpression Id. */
  int QUIT = 19;
  /** RegularExpression Id. */
  int AND = 20;
  /** RegularExpression Id. */
  int OR = 21;
  /** RegularExpression Id. */
  int TYPE_INT = 22;
  /** RegularExpression Id. */
  int TYPE_SERIAL = 23;
  /** RegularExpression Id. */
  int TYPE_VARCHAR = 24;
  /** RegularExpression Id. */
  int SEMICOLON = 25;
  /** RegularExpression Id. */
  int COMMA = 26;
  /** RegularExpression Id. */
  int LPAREN = 27;
  /** RegularExpression Id. */
  int RPAREN = 28;
  /** RegularExpression Id. */
  int STAR = 29;
  /** RegularExpression Id. */
  int OP_EQ = 30;
  /** RegularExpression Id. */
  int OP_GT = 31;
  /** RegularExpression Id. */
  int OP_LT = 32;
  /** RegularExpression Id. */
  int NUMBER = 33;
  /** RegularExpression Id. */
  int STRING = 34;
  /** RegularExpression Id. */
  int ID = 35;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "\"CREATE\"",
    "\"TABLE\"",
    "\"DROP\"",
    "\"INSERT\"",
    "\"INTO\"",
    "\"VALUES\"",
    "\"DELETE\"",
    "\"FROM\"",
    "\"WHERE\"",
    "\"SELECT\"",
    "\"AS\"",
    "\"TABLES\"",
    "\"EXIT\"",
    "\"QUIT\"",
    "\"AND\"",
    "\"OR\"",
    "\"INT\"",
    "\"SERIAL\"",
    "\"VARCHAR\"",
    "\";\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"*\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "<NUMBER>",
    "<STRING>",
    "<ID>",
  };

}
